app:
  name: auto_migration_example
  ver: 1.0.0
  host: 0.0.0.0
  port: 8080

  db_migration:
    auto_migrate: true
    force_migrate: true
    version: up

  middleware:
    mysql:
      default:
        _startup: true
        dsn: "root:password@tcp(localhost:3306)/xx?charset=utf8&parseTime=true&loc=Local"
