app:
  host: 0.0.0.0
  middleware:
    cache:
      default:
        backend_type: redis
        name: default
    grpc:
      client:
        app:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        approve:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        default:
          addr: :1114
          timeout_per_request: 300s
          with_insecure: true
        job:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        license:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        monitor:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        notice:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        project:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        rbac:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        storage:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        sysconfig:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
        user:
          addr: :1114
          naming: false
          timeout_per_request: 300s
          with_insecure: true
      server:
        default:
          _startup: true
          addr: :1114
          max_recv_msg_size: 4194304
          max_send_msg_size: 2147483647
    kafka:
      cluster_addr:
      - 10.0.4.48:9092
      startup: true
    logger:
      log_dir: ./log
    monitor:
      _startup: true
      listen: :9101
      metric: /metrics
      prometheus_server_endpoint: http://10.0.4.48:9090
    mysql:
      default:
        _startup: true
        dsn: ticp_user:ticp6655@tcp(10.0.4.48:3306)/ticp_portal?charset=utf8&parseTime=true&loc=Local
    redis:
      default:
        _startup: true
        addr: 10.0.4.48:6379
  name: pspd
  port: 32432
  ver: 1.0.0
