app:
  name: sysconfig
  ver: 1.0.0

  host: 0.0.0.0
  port: 8889

  # load config from etcd?
  load_remote_config: false

  middleware:
    logger:
      log_dir: ./log

    monitor:
      _startup: false
      listen: ":9101"
      metric: "/metrics"

    mysql:
      default:
        _startup: true
        dsn: "root:password@tcp(localhost:3306)/xx?charset=utf8&parseTime=true&loc=Local"

    grpc:
      server:
        default:
          _startup: true
          addr: :1114

      client:
