app:
  db_migration:
    auto_migrate: true
    force_migrate: false
    version: up
  host: 0.0.0.0
  middleware:
    cache:
      default:
        backend_type: redis
        name: default
    etcd:
      endpoints:
      - etcd:2379
      startup: true
      tls: false
    grpc:
      client:
        idgen:
          addr: idgen:11211
          naming: false
          timeout_per_request: 5s
          with_insecure: true
        job:
          addr: job:11211
          naming: false
          timeout_per_request: 5s
          with_insecure: true
      server:
        default:
          _startup: true
          addr: :11211
    kafka:
      cluster_addr:
      - kafka:9092
      startup: true
    logger:
      log_dir: ./log
    monitor:
      _startup: true
      listen: :9090
      metric: /metrics
    mysql:
      default:
        _startup: true
        dsn: ticp_user:ticp6655@tcp(10.0.4.48:3306)/ticp?charset=utf8&parseTime=true&loc=Local
    redis:
      default:
        _startup: true
        addr: redis:6379
    tracing:
      database:
        binding: true
        enabled: true
      details:
        enabled: true
        request: true
        response: false
      jaeger:
        endpoint: http://0.0.0.0:14268/api/traces
      startup: true
  name: license
  port: 8899
  ver: 1.0.0
