app:
  name: app
  ver: 1.0.0
  host: 0.0.0.0
  port: 8889

  middleware:
    monitor:
      _startup: true
      listen: ":9102"
      metric: "/metrics"
      prometheus_server_endpoint: "http://localhost:9090"

    mysql:
      default:
        _startup: true
        encrypt: false
        dsn: "root:password@tcp(localhost:3306)/xx?charset=utf8&parseTime=true&loc=Local"

    grpc:
      server:
        default:
          _startup: true
          addr: :1114
          max_recv_msg_size: 4194304
          max_send_msg_size: 2147483647

      client:
        rbac:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

        user:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

        monitor:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

        storage:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

        notice:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

        license:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

        approve:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

        default:
          addr: :1114
          timeout_per_request: "300s"
          with_insecure: true

    apm:
      startup: false
      apm_server_url: "http://:8200"

    kafka:
      startup: true
      cluster_addr:
        - ":9092"

    cache:
      default:
        name: default
        backend_type: redis

    redis:
      default:
        _startup: true
        addr: :6379
