app:
  name: storage
  ver: 1.0.0
  host: 0.0.0.0
  port: 2225

  middleware:
    logger:
      log_dir: ./log

    monitor:
      _startup: false
#      listen: 0.0.0.0:9999

    mysql:
      default:
        _startup: true
        dsn: "root:password@tcp(localhost:3306)/xx?charset=utf8&parseTime=true&loc=Local"

    redis:
      default:
        _startup: true
        addr: :6379

    grpc:
      server:
        default:
          _startup: true
          #type: static or naming
          addr: :1115 # service name

      client:
        default:
          addr: :1111

          # golang duration format, such as "300ms", "-1.5h" or "2h45m".
          # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
          timeout_per_request: "5s"

          with_insecure: true
        user:
          addr: ":1113"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true
        notice:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true
        approve:
          addr: ":1115"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true
        project:
          addr: ":1117"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true
    cache:
      default:
        name: default
        backend_type: redis

    apm:
      startup: false
      apm_server_url: "http://:8200"
