app:
  db_migration:
    auto_migrate: true
    force_migrate: false
    version: up
  host: 0.0.0.0
  load_remote_config: false
  middleware:
    cache:
      default:
        backend_type: redis
        name: default
    etcd:
      endpoints:
      - etcd:2379
      startup: false
      tls: false
    grpc:
      client:
        company:
          addr: 10.0.4.48:11214
          naming: false
          timeout_per_request: 5s
          with_insecure: true
        default:
          addr: ''
          timeout_per_request: 15s
          with_insecure: true
        idgen:
          addr: idgen:11211
          timeout_per_request: 5s
          with_insecure: true
      server:
        default:
          _startup: true
          addr: :11211
          max_concurrent_streams: 100
    logger:
      log_dir: ./log
    monitor:
      _startup: true
      listen: :9101
      metric: /metrics
    mysql:
      default:
        _startup: true
        dsn: ticp_user:ticp6655@tcp(10.0.4.48:3306)/ticp?charset=utf8&parseTime=true&loc=Local
    redis:
      default:
        _startup: true
        addr: redis:6379
  name: hydra_lcp
  network_if_name: ''
  port: 9091
  ver: 1.0.0
