app:
  name: approve
  ver: 1.0.0

  host: 0.0.0.0
  port: 8892

  # load config from etcd?
  load_remote_config: false

  middleware:
    logger:
      log_dir: ./log

    monitor:
      _startup: false
      listen: ":9101"
      metric: "/metrics"

    mysql:
      default:
        _startup: true
        dsn: "root:password@tcp(localhost:3306)/xx?charset=utf8&parseTime=true&loc=Local"

    grpc:
      server:
        default:
          _startup: true
          addr: :1114

      client:
        default:
          addr: :1114

          # golang duration format, such as "300ms", "-1.5h" or "2h45m".
          # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
          timeout_per_request: "5s"

          with_insecure: true
          ##复杂配置

          #with_write_buffer_size: 32768
          #with_initial_window_size: 65536
          #with_initial_conn_window_size: 65536
          #with_max_msg_size: 2147483647
          #with_backoff_max_delay: 10
          #with_block: true
          #with_timeout: 0
          ##返回临时请求错误，但自己不是临时请求设置为true
          #fail_on_non_temp_dial_error: true
          #with_user_agent: grpc-demo-app
          ##with_insecure: true时有效
          #with_authority: demo-app
          #with_channelz_parent_id: 1
          #with_disable_service_config: true
          ##禁止重试(默认关闭)
          #with_disable_retry: true
          #with_max_header_list_size: 1024
          ##关闭健康检查
          #with_disable_health_check: true
          ##keepalive配置
          #keepalive_time: 70000
          #keepalive_timeout: 80000
          #keepalive_permit_without_stream: true
        rbac:
          addr: ":1118"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true
        user:
          addr: ":1113"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true
        notice:
          addr: ":1113"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true
        sysconfig:
          addr: ":1114"
          naming: false
          timeout_per_request: "300s"
          with_insecure: true

