email:
    enable: false
    setting:
        host: smtp.example.com
        port: 587
        tls: true
        send_email: test@example.com
        password: 1234
    template:
        - content: |
            您好！邮件发送成功!
          subject: 测试发送邮件
          type: Default
        - content: |
            您好！<br/> 恭喜您成功开通了账号！<br/> 用户名为：{{.Username}}
          subject: 账号开通成功 {{.Datetime}}
          type: CreateAccount
