app:
  db_migration:
    auto_migrate: true
    force_migrate: false
    version: up
  host: 0.0.0.0
  middleware:
    grpc:
      client:
        hydra_lcp:
          addr: hydra_lcp:11211
          naming: false
          timeout_per_request: 5s
          with_insecure: true
    mysql:
      default:
        _startup: true
        dsn: ticp_user:ticp6655@tcp(10.0.4.48:3306)/ticp?charset=utf8&parseTime=true&loc=Local
  name: iamserver
  port: 8899
  ver: 1.0.0
