alerting:
  alertmanagers:
  - static_configs:
    - targets: null
global:
  evaluation_interval: 60s
  scrape_interval: 60s
rule_files:
- /etc/prometheus/rules.yml
scrape_configs:
- job_name: local pc
  static_configs:
  - labels:
      instance: local-pc
    targets:
    - 10.0.4.48:9100
